[project]
group   = "$organization$"
name    = "$name$"
version = "0.1.0"
jdk     = $jdk$
java    = $jdk$

[application]
main = "$package$.Main"

[dependencies]
jline = { group = "org.jline", name = "jline", version = "$jline$" }

[test-dependencies]
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version = "=5.11.4" }
