group = "$organization$"
name = "$name$"
version = "0.1.0"
kotlin = "latest"

[application]
main = "$package$.ApplicationKt"
assembly = true

[micronaut]
version = "latest"

[dependencies]
micronaut-http-server-netty = { group = "io.micronaut", name = "micronaut-http-server-netty" }
micronaut-jackson-databind = { group = "io.micronaut", name = "micronaut-jackson-databind" }
logback = { group = "ch.qos.logback", name = "logback-classic" }

[processor-dependencies]
micronaut-inject-java = { group = "io.micronaut", name = "micronaut-inject-java" }

[test-dependencies]
micronaut-test-junit5 = { group = "io.micronaut.test", name = "micronaut-test-junit5" }
micronaut-http-client = { group = "io.micronaut", name = "micronaut-http-client" }
junit-jupiter = "latest"
