[project]
group   = "$organization$"
name    = "$name$"
version = "0.1.0"
jdk     = $jdk$
java    = $jdk$
kotlin  = "$kotlin$"

[application]
main = "$package$.ApplicationKt"

[spring-boot]
version = "$spring_boot$"

[dependencies]
starter-webmvc     = { group = "org.springframework.boot", name = "spring-boot-starter-webmvc" }
starter-validation = { group = "org.springframework.boot", name = "spring-boot-starter-validation" }
starter-actuator   = { group = "org.springframework.boot", name = "spring-boot-starter-actuator" }
starter-data-jpa   = { group = "org.springframework.boot", name = "spring-boot-starter-data-jpa" }
h2                 = { group = "com.h2database", name = "h2" }
kotlin-reflect     = { group = "org.jetbrains.kotlin", name = "kotlin-reflect", version = "=$kotlin$" }
jackson-kotlin     = { group = "com.fasterxml.jackson.module", name = "jackson-module-kotlin" }

[dev-dependencies]
devtools = { group = "org.springframework.boot", name = "spring-boot-devtools" }

[test-dependencies]
starter-test = { group = "org.springframework.boot", name = "spring-boot-starter-test" }
